apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingAdmissionPolicy
metadata:
  name: disallow-default-project
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:   ["apps"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["deployments"]
  validations:
    - expression: "object,spec.template.spec.containers.all(container,has(container.readinessProbe))"
      message: "Deployments must have a defined readiness probe"
      reason: Invalid
    - expression: "object,spec.template.spec.containers.all(container,has(container.livenessProbe))"
      message: "Deployments must have a defined liveness probe"
      reason: Invalid
